roles: apt-cacher-ng: zchunk files need to be "volatile"
Seems buggy, but if you don't, then the next update fails with:


Errors during downloading metadata for repository 'updates':
  - Interrupted by header callback: Server reports Content-Length: 8378 but expe
cted size is: 1
  - Zchunk header checksum didn't match expected checksum
Error: Failed to download metadata for repo 'updates': Yum repo downloading erro
r: Downloading error(s): repodata/541a98b0267c4e14383bbdc1047d4fbbe821a6b09a2f00
c3e3404b8a357aed56-updateinfo.xml.zck - Cannot download, all mirrors were alread
y tried without success